Add Credential Revocation Contracts
hyperledger/indy-besu pull request #54
Opened 2024-06-29 19:54 UTC by vdsilveira

**Summary of Changes:**

***Addition of Contracts for Credential Revocation:***

- Added a folder named revoke to the contracts directory containing the smart contracts related to credential revocation.
 - Included the revocation contract in genesis.json.

***Modifications to Other Contracts:***

- Added errors related to revocation in AnouncredsErrors.sol.

 - Modified the ecrecover method to use the standardized ECDSA method from the OpenZeppelin library in the following contracts:
   - CredentialDefinitionRegistry
   - CredentialDefinitionRegistryInterface
   - SchemaRegistry
   - SchemaRegistryInterface
   - IndyDidRegistry
   - IndyDidRegistryInterface

2024-07-01 14:40 UTC, Toktar requested changes
@vdsilveira Thank you a lot! We were thinking about adding revocations for a long time.
Right now, this implementation looks like DID Document status that already exists. Also, I have some questions about using credential identifiers.
Could you please start with design and when we discuss it, add tests, SDK functionality, wrappers and examples/demo?
Glad to have the opportunity to work with you

2024-07-01 14:40 UTC, Toktar commented on smart_contracts/contracts/did/IndyDidRegistry.sol
> -     */
Could you not to remove the codebase documentation?

2024-07-01 14:40 UTC, Toktar commented on smart_contracts/contracts/did/IndyDidRegistry.sol
> -        address actor, // actor is either message sender in case of `createDid` or signer in case of `createDidSigner`
The same ask for comments and documentation

2024-07-02 12:33 UTC, closed without merging

2024-07-11 13:51 UTC, vdsilveira commented
I'm closing this PR to refactor the code, including the tests, wrappers and so on.